# -*- coding: utf-8 -*-
"""PS4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Olfi89un-O7-O7X0LM9HSw-uTBgUcIyF
"""

# input elements
nmk = list(map(int, input().split())) 

# num of circular plots
n = nmk[0]

# num of circular houses
m = nmk[1]

# num of square houses
k = nmk[2]

plotList = list(map(float, input().split()))
mList = list(map(float, input().split()))
kList = list(map(float, input().split()))

for i in range(0, k):
    val = kList[i]
    sqrt = 2**0.5
    val = val/sqrt
    kList[i] = val

houseList = mList + kList
houseList.sort()
plotList.sort()

countList = []

for i in range(0,n):
  if plotList[i] > houseList[i]:
    countList.append(1)

print(len(countList))

